### ISSUE TITLE
Different users for bird tree

### ISSUE THREAD

**Issue by wcornwell** [coreytcallaghan/eBirder-visualizations#6]
Be good to be able to show a few people there own data to start with.

**Comment by coreytcallaghan** [comment]
Agreed. I just added a friend of mine's data into the repo. Will maybe ask Rich Fuller if he'd download and send his along, as it would be a lot more species than mine! https://ebird.org/ebird/australia/profile/Mjg0NTY3/world

**Comment by coreytcallaghan** [comment]
And, John quickly accomplished this as well!
